datasource:
  url: 39.101.200.69:3306/GeiGei

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://${datasource.url}?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
     username: root
     password: xzl1122
     hikari:
      maximum-pool-size: 10 # 最大连接池数
      max-lifetime: 1770000



mybatis:
  # 指定别名设置的包为所有entity
  type-aliases-package: com.itcodai.course01.entity
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名规范
  mapper-locations: # mapper映射文件位置
     - classpath:mapper/*.xml

logging:
  config: logback.xml
  level:
    com.itcodai.course01.dao: trace

url:
  orderUrl: http://localhost:8002
  userUrl: http://localhost:8003
  shoppingUrl: http://localhost:8004
